apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  APP_ENV: "production"
  FILESYSTEM_DISK: "local" # App thinks it's local but it's EFS
---
apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
type: Opaque
data:
  # In real life, use ExternalSecrets Operator or AWS Secrets Manager
  DB_PASSWORD: "CHANGE_ME_BASE64"  
